name: Maven Build

on:
  workflow_dispatch:
  push:
    branches:
      - backend

jobs:
  test_and_build:
    name: Test
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install and Test
        run: |
          apt-get update && apt-get -y install maven 
          mvn clean test

      - name: Build java
        run: |
          mvn clean package

      
