name: Build frontend app

on:
  workflow_dispatch:
  push:
    branches:
      - front2
    paths:
      - '.github/workflows/frontend.ci.yml'
     

env:
  USER: ${{ github.actor }}
  GH_TOKEN: ${{ secrets.GH_TOKEN2 }}
  REGISTRY: ghcr.io
  IMAGE_NAME: bootcamp-frontend
  IMAGE_VERSION: 1.0.0


jobs:
  build_node:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Atualizar repositórios do sistema
      run: sudo apt-get update

    - name: Instalar npm
      run: sudo apt-get -y install npm

    - name: Instalar Angular CLI
      run: sudo npm install -g @angular/cli

  #  - name: Executar testes
 #   run: ng test



